// <auto-generated />
using System;
using Bioskop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bioskop.Migrations
{
    [DbContext(typeof(BioskopContext))]
    [Migration("20210806212407_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bioskop.Models.BioskopK", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnName("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnName("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bisokop");
                });

            modelBuilder.Entity("Bioskop.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Glumci")
                        .HasColumnName("Glumci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnName("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zanr")
                        .HasColumnName("Zanr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vremeTrajanja")
                        .HasColumnName("VremeTrajanja")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("Bioskop.Models.FilmSala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FilmID")
                        .HasColumnType("int");

                    b.Property<int?>("SalaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FilmID");

                    b.HasIndex("SalaID");

                    b.ToTable("FilmSala");
                });

            modelBuilder.Entity("Bioskop.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BioskopID")
                        .HasColumnType("int");

                    b.Property<int>("BrojSedista")
                        .HasColumnName("BrojSedista")
                        .HasColumnType("int");

                    b.Property<string>("Oznaka")
                        .HasColumnName("Oznaka")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BioskopID");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("Bioskop.Models.FilmSala", b =>
                {
                    b.HasOne("Bioskop.Models.Film", "Film")
                        .WithMany("FilmSala")
                        .HasForeignKey("FilmID");

                    b.HasOne("Bioskop.Models.Sala", "Sala")
                        .WithMany("FilmSala")
                        .HasForeignKey("SalaID");
                });

            modelBuilder.Entity("Bioskop.Models.Sala", b =>
                {
                    b.HasOne("Bioskop.Models.BioskopK", "Bioskop")
                        .WithMany("Sale")
                        .HasForeignKey("BioskopID");
                });
#pragma warning restore 612, 618
        }
    }
}
